<a href="https://colab.research.google.com/github/Aroson22/Cmda_exam/blob/main/Python_basic_lesson_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python basic lesson 4

From last time:

In [2]:
import time
import numpy as np

N = 10000000

start_time = time.time()

l = []

for i in range(N):
  l.append(i**2)

elapsed_time = time.time() - start_time
print("pure.-python:", elapsed_time)

start_time = time.time()
a = np.arange(N)**2
elapsed_time = time.time() - start_time

print("numpy:", elapsed_time)

pure.-python: 4.21593713760376
numpy: 0.06381750106811523


Il vantaggio sistematico degli array numpy è che anche se ho una limitatezza su ciò che posso metterci dentre: deve essere tutto dello stesso tipo. Però specificando il tipo so già a priori quanta memoria occupano e quindi posso analizzare la memoria a blocchi di bit ( ex float: 8 bit, guardo i primi 8 e poi i secondi 8 e così via) risparmio un tempo considerevole!!!

In [3]:
#address of the object
id(a)


136912721287600

# Broadcasting
https://numpy.org/doc/stable/user/basics.broadcasting.html

In [10]:
a = np.ones((3,2))
a


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
b= a*2  # moltiplicazione fra array e scalari
b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [8]:
c = np.array([1.,2.,3.])
c

array([1., 2., 3.])

In [11]:
a*c

ValueError: ignored

In [12]:
c*a

ValueError: ignored

In [14]:
d = np.array([1.,2.])
d

array([1., 2.])

In [15]:
a*d

array([[1., 2.],
       [1., 2.],
       [1., 2.]])

In [16]:
d*a

array([[1., 2.],
       [1., 2.],
       [1., 2.]])

il Broadcast sono operazioni molto potenti che posso fare sugli array, sotto specifiche condizioni, numpy è in grado di capire la cosa più smart da fare

In [18]:
a.T #.T trasposto della matrice

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
(a*d).T

array([[1., 1., 1.],
       [2., 2., 2.]])

In [17]:
a.T *c

array([[1., 2., 3.],
       [1., 2., 3.]])

Ora funziona, ma ho qualcosa di diverso rispetto a quello da cui sono partito

In [24]:
a = np.random.normal(size =( 10 , 5)) # estrae da un gaussiana a media nulla e varianza unitaria una matrice--> tramite size 10*5
a

array([[ 0.40561688,  1.32502588,  1.91825798,  0.53252049,  0.16572686],
       [ 0.59401739,  0.29565698, -0.0606578 ,  1.07049048,  1.72053898],
       [ 0.10027021, -0.31211207, -0.26864104, -0.09825474, -0.20717112],
       [-0.18416497,  0.01470462,  0.0176534 ,  0.9454242 , -0.72567328],
       [ 0.09290552,  1.0687947 , -0.59023221, -0.52755397,  0.61545332],
       [-0.14115054,  1.27203286, -0.86748726,  0.99409082, -0.1632648 ],
       [ 2.21538086, -1.55064331,  1.56548119, -0.95930615, -0.2803212 ],
       [ 0.37601995,  0.08236184, -0.79098822,  0.64497141, -1.48059038],
       [-0.2662853 ,  1.00971699, -0.95243339, -1.23715527,  0.32080553],
       [ 1.80248959,  0.84569312, -0.18996985,  1.83594553, -1.1127478 ]])

---
***Power method:***

In [26]:
np.power(a,a) # array 1 elevato all'array 2

<ipython-input-26-76baf79b9599>:1: RuntimeWarning: invalid value encountered in power
  np.power(a,a)


array([[0.69349805, 1.45194592, 3.48890093, 0.71493817, 0.74239055],
       [0.73389304, 0.69748491,        nan, 1.0756429 , 2.54372401],
       [0.79404899,        nan,        nan,        nan,        nan],
       [       nan, 0.93983822, 0.93121629, 0.94832436,        nan],
       [0.80190951, 1.07369781,        nan,        nan, 0.74175321],
       [       nan, 1.35807987,        nan, 0.99412564,        nan],
       [5.82505153,        nan, 2.01705413,        nan,        nan],
       [0.69226252, 0.81413646,        nan, 0.7536315 ,        nan],
       [       nan, 1.00981187,        nan,        nan, 0.69438392],
       [2.89206466, 0.86784939,        nan, 3.05092975,        nan]])

In [27]:
a_1 = np.array([1.,2.,3.,4.,5.])
b_1 = np.array([1.,3.,2.,6.,10.])
np.power(a_1,b_1)

array([1.000000e+00, 8.000000e+00, 9.000000e+00, 4.096000e+03,
       9.765625e+06])

---

In [28]:
np.mean(a) # media dei valori di a (matrice e/o vettore)

0.21762485805088236

---

In [30]:
np.mean(a, axis = 0) # media delle colonne

array([ 0.49950996,  0.40512316, -0.02190172,  0.32011728, -0.11472439])

In [31]:
np.mean(a,axis = 1) # media delle righe

array([ 0.86942962,  0.72400921, -0.15718175,  0.01358879,  0.13187347,
        0.21884422,  0.19811828, -0.23364508, -0.22507029,  0.63628212])

In [ ]:
np.mean(a,axis = 2) # ERROR!!!

---

In [33]:
np.std(a) # standard deviation dei valori di a (matrice e/o vettore)

0.9135223737947504

***Basic indexing:***

In [35]:
a[0,0] # prim riga prima colonna

0.4056168823419888

In [36]:
a[0,1] #prima riga seconda colonna

1.3250258776865265

In [37]:
a[2] #terza riga

array([ 0.10027021, -0.31211207, -0.26864104, -0.09825474, -0.20717112])

In [38]:
a[:,3] #quarta colonna

array([ 0.53252049,  1.07049048, -0.09825474,  0.9454242 , -0.52755397,
        0.99409082, -0.95930615,  0.64497141, -1.23715527,  1.83594553])

In [40]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
a = a.reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
a[2:4,0:3]

array([[ 8,  9, 10],
       [12, 13, 14]])

# VECTORIZATION


Ritornando allo script ad inizio lezione, anche se il primo è molto più lento è più chiaro che cosa fa ( i codici si scrivono una volta e si leggono molte)


```
 for i in range(N):
  l.append(i**2)


a = np.arange(N)**2

```
***np.arange*** è la versione *VETTORIZZATA* del ciclo for scritto sopra: le funzioni e i metodi mostrati precedentemente rendono possibile la *Vettorizzazione*


---


In [56]:
#CALORIMETRO MISURA

import random
import time


import numpy as np
import matplotlib.pyplot as plt

TRUE_ENERGY = 100 #Gev
SATURATION_ENERGY = 107 #Gev
ENERGY_RESOLUTION = 0.05 # 5%
N = 100000000000
meas_energy = []

def python_cal():
  """

  """
  start_time = time.time()
  for i in range(N):
    E = TRUE_ENERGY  * random.normalvariate(1.,ENERGY_RESOLUTION)
    if E >= SATURATION_ENERGY:
      E = SATURATION_ENERGY
      meas_energy.append(E)

  elapsed_time = time-time() - start_time


  plt.figure("Pure python",elapsed_time)
  plt.hist(meas_energy,bins = np.linspace(80.,120.,100))





KeyboardInterrupt: ignored

---

vectorize

---

In [58]:
#CALORIMETRO MISURA

import random
import time


import numpy as np
import matplotlib.pyplot as plt

ENERGY = 100 #Gev
SATURATION_ENERGY = 107#Gev
ENERGY_RESOLUTION = 0.05 # 5%
N = 100000000000

def numpy_cal():
  """

  """
  start_time = time.time()

  meas_energy = ENERGY  * np.random.normal(1.,ENERGY_RESOLUTION,size = N)
  mask = meas_energy >= SATURATION_ENERGY #MASKING: https://numpy.org/doc/stable/reference/maskedarray.generic.html


  elapsed_time = time-time() - start_time


  plt.figure("numpy",elapsed_time)
  plt.hist(meas_energy,bins = np.linspace(80.,120.,100))




In [ ]:
numpy_cal()
plt.show()

In [ ]:

python_cal()
plt.show()

---

# MASKING:
https://numpy.org/doc/stable/reference/maskedarray.generic.html

Crea un vettore booleano lungo quanto il vettore maskato con valori True se la condizione è rispettata e False al contrario


```

import numpy as np
import numpy.ma as ma
x = np.array([1, 2, 3, -1, 5])

#We wish to mark the fourth entry as invalid.

mx = ma.masked_array(x, mask=[0, 0, 0, 1, 0])

x.mean()
mx.mean()

```
---

Non sempre la vettorizzazione è vantaggiosa e utile, in alcuni casi peggiora: quando non conosco la lunghezza dei vettori in gioco!

**DETECTOR EXAMPLE:** *NON CONOSCO QUANTE PAIA DI PARTICELLE E ANTIPARTICELLE IL MIO ELETTRONE GENERA DURANTE L'INTERAZIONE*